name: CI

on:
  push:
    branches:
      - main
      - 'bo_Comfyui'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: [3.10]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m venv venv
          venv\Scripts\activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          venv\Scripts\activate
          pytest
